import { useRef, useState } from "react";
import { AccessibilityInfo, Image, Linking, Modal, Pressable, StyleSheet, Text, TextInput, View, useWindowDimensions } from "react-native";
import * as ImagePicker from "expo-image-picker";
import * as SecureStore from "expo-secure-store";
import type { OfflineDemoAction, OfflineDemoState } from "./offline-demo";


type Props={readonly state:OfflineDemoState;readonly onAction:(action:OfflineDemoAction)=>void};
type Filter="All"|"Open"|"Resolved";
type IconName="chat"|"whatsapp"|"ticket"|"check"|"clock"|"headset"|"clip"|"send"|"phone"|"chevron"|"minus";
type Ticket={id:string;subject:string;context:string;date:string;status:"IN REVIEW"|"RESOLVED";update:string};
const C={orange:"#dc7600",gold:"#eba000",ink:"#20211f",paper:"#fffefb",ivory:"#fbf9f4",line:"#e6e3de",muted:"#686b70",green:"#21aa27"};
const tickets:Ticket[]=[
 {id:"KG-1019",subject:"Project update notification delayed",context:"Amaravati Riverfront District",date:"05 Aug 2026",status:"RESOLVED",update:"Resolved 06 Aug 2026"},
 {id:"KG-0987",subject:"Change registered phone number",context:"Account & Access",date:"22 Jul 2026",status:"RESOLVED",update:"Resolved 22 Jul 2026"},
];
const projects=["Aarohan Medical City","Amaravati Riverfront District","Amaravati Solar Commons"] as const;
const SUBJECT_MAX=100, DESCRIPTION_MAX=1000;
function Icon({name,color=C.orange,size=22}:{name:IconName;color?:string;size?:number}){
 const box={width:size,height:size};
 if(name==="clock"||name==="check") return <View style={[box,ic.circle,{borderColor:color}]}>{name==="check"?<><View style={[ic.checkA,{backgroundColor:color}]}/><View style={[ic.checkB,{backgroundColor:color}]}/></>:<><View style={[ic.clockA,{backgroundColor:color}]}/><View style={[ic.clockB,{backgroundColor:color}]}/></>}</View>;
 if(name==="chat") return <View style={[box,ic.chat]}><View style={[ic.chatA,{borderColor:color}]}/><View style={[ic.chatB,{borderColor:color}]}/></View>;
 if(name==="whatsapp") return <View style={[box,ic.circle,{borderColor:color,borderWidth:2}]}><View style={[ic.phoneMini,{borderColor:color}]}/></View>;
 if(name==="ticket") return <View style={[box,ic.ticket,{borderColor:color}]}><View style={[ic.rule,{backgroundColor:color}]}/><View style={[ic.rule,ic.rule2,{backgroundColor:color}]}/></View>;
 if(name==="headset") return <View style={[box,ic.headset,{borderColor:color}]}><View style={[ic.mic,{borderColor:color}]}/></View>;
 if(name==="clip") return <View style={[box,ic.clipFrame]}><View style={[ic.clipOuter,{borderColor:color}]}><View style={[ic.clipInner,{borderColor:color}]}/></View></View>;
 if(name==="send") return <View style={[box,ic.send,{borderColor:color}]}/>;
 if(name==="phone") return <View style={[box,ic.phone,{borderColor:color}]}/>;
 if(name==="minus") return <View style={[box,ic.minus,{backgroundColor:color}]}/>;
 return <View style={[box,ic.arrow]}><View style={[ic.arrowLine,{backgroundColor:color}]}/><View style={[ic.arrowHead,{borderColor:color}]}/></View>;
}
export function DemoSupportExperience({onAction,state}:Props){
 const {width}=useWindowDimensions(); const narrow=width<350;
 const [project,setProject]=useState<string>(projects[0]),[category,setCategory]=useState(""),[subject,setSubject]=useState(""),[description,setDescription]=useState(""),[ticketAttachment,setTicketAttachment]=useState(""),[chatAttachment,setChatAttachment]=useState(""),[message,setMessage]=useState("");
 const [priority,setPriority]=useState<"Normal"|"Urgent">("Normal"),[errors,setErrors]=useState(false),[notice,setNotice]=useState(""),[messages,setMessages]=useState<string[]>([]),[filter,setFilter]=useState<Filter>("All"),[chatMin,setChatMin]=useState(()=>{try{return SecureStore.getItem("karaa.support.chat-minimised")==="true"}catch{return false}}),[submitting,setSubmitting]=useState(false);
 const [modal,setModal]=useState<"hours"|"ticket"|"category"|"project"|"document"|null>(null),[selected,setSelected]=useState<Ticket|null>(null);
 const subjectRef=useRef<TextInput>(null);
 const toggleChat=()=>setChatMin(v=>{const next=!v;SecureStore.setItemAsync("karaa.support.chat-minimised",String(next)).catch(()=>undefined);return next});
 const pick=async(target:"ticket"|"chat")=>{try{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],quality:.7});if(r.canceled)return;const asset=r.assets?.[0];if(!asset){setNotice("No image was returned by the photo picker.");return}const name=asset.fileName||"Selected photo";(target==="ticket"?setTicketAttachment:setChatAttachment)(name);setNotice(`${name} attached to ${target === "ticket" ? "this ticket" : "live chat"}.`)}catch{setNotice("The photo picker could not be opened. Please try again.")}};
 const submit=()=>{const invalid=!category||!subject.trim()||!description.trim()||subject.trim().length>SUBJECT_MAX||description.trim().length>DESCRIPTION_MAX;if(invalid){setErrors(true);setNotice("");return}if(submitting)return;setSubmitting(true);try{onAction({type:"create-support-ticket",projectOrCategory:`${project} · ${category}`,subject:subject.trim(),description:description.trim(),priority:priority.toLowerCase() as "normal"|"urgent"});setCategory("");setSubject("");setDescription("");setTicketAttachment("");setPriority("Normal");setErrors(false);setNotice("Demo ticket created locally on this device — nothing was sent to a support backend.")}finally{setSubmitting(false)}};
 const send=()=>{const body=message.trim();if(body){const supportThread=state.chatThreads.find(thread=>thread.kind==="support");if(supportThread)onAction({type:"send-chat-message",threadId:supportThread.id,body});setMessages(v=>[...v,body]);setMessage("")}};
 const openUrl=(u:string)=>Linking.openURL(u).catch(()=>setNotice("This device could not open the requested app."));
 const canonical:Ticket[]=[...state.supportTickets.map(t=>({id:t.id,subject:t.subject,context:t.projectOrCategory,date:t.createdLabel,status:t.status==="resolved"?"RESOLVED" as const:"IN REVIEW" as const,update:t.updatedLabel})),...tickets];
 const shown=canonical.filter(t=>filter==="All"||(filter==="Open"?t.status==="IN REVIEW":t.status==="RESOLVED"));
 return <View style={s.page} testID="customer-support-page">

  <View style={s.hero}><View style={s.heroCopy}><Text style={s.eyebrow}>HELP & ASSISTANCE</Text><Text style={s.heroTitle}>Support</Text><Text style={s.heroSub}>We’re here to help with your projects,{`\n`}documents and account.</Text></View><Image accessibilityLabel="Karaa support specialist" resizeMode="cover" source={require("../../assets/support/support-specialist-hero.webp")} style={s.heroImage}/><View style={s.heroFade}/></View>
  <View style={s.content}>
   <View style={s.overview}><Text style={s.overline}>Your support</Text><View style={s.metrics}><Metric icon="ticket" n={String(canonical.filter(t=>t.status==="IN REVIEW").length).padStart(2,"0")} l="Open Ticket"/><Metric icon="check" n={String(canonical.filter(t=>t.status==="RESOLVED").length).padStart(2,"0")} l="Resolved"/><Metric icon="clock" n="< 2 hrs" l="Avg. Response" last/></View><View style={s.online}><View style={s.row}><View style={s.greenDot}/><Text style={s.onlineText}>Support team online</Text></View><Pressable accessibilityRole="button" accessibilityLabel="View service hours" onPress={()=>setModal("hours")} style={s.hit}><Text style={s.orangeLink}>View service hours</Text><Icon name="chevron" size={14}/></Pressable></View></View>
   <Text style={s.sectionTitle}>How can we help?</Text><View style={s.quickRow}><Quick icon="chat" title="Live Chat" sub="Chat now" online onPress={()=>{setChatMin(false);setNotice("Live chat is ready below. Type a message to continue.");AccessibilityInfo.announceForAccessibility("Live chat opened")}}/><Quick icon="ticket" title="Raise Ticket" sub="Report an issue" onPress={()=>{subjectRef.current?.focus();setNotice("Request form focused.");AccessibilityInfo.announceForAccessibility("Raise a request form")}}/></View>
   <View style={[s.twoCol,narrow&&s.stacked]}><View style={s.panel}><Text style={s.panelTitle}>Raise a request</Text><Text style={s.panelSub}>Tell us what went wrong and{`\n`}our team will assist you.</Text><Label t="Related project"/><Select label={`Select project ${project}`} value={project} onPress={()=>setModal("project")}/><Label t="Issue category"/><Select label="Issue category" value={category||"Select a category"} muted={!category} invalid={errors&&!category} onPress={()=>setModal("category")}/><Label t="Subject"/><TextInput ref={subjectRef} accessibilityLabel="Subject" maxLength={SUBJECT_MAX} placeholder="Briefly describe the issue" placeholderTextColor="#98999d" value={subject} onChangeText={setSubject} style={[s.input,errors&&!subject.trim()&&s.invalid]}/><Label t="Description"/><TextInput accessibilityLabel="Description" maxLength={DESCRIPTION_MAX} placeholder="Share the details of your request" placeholderTextColor="#98999d" multiline value={description} onChangeText={setDescription} style={[s.input,s.area,errors&&!description.trim()&&s.invalid]}/><Pressable accessibilityRole="button" accessibilityLabel="Add photo to ticket" onPress={()=>pick("ticket")} style={s.upload}><Icon name="clip" color={C.ink} size={17}/><View><Text style={s.uploadTitle}>{ticketAttachment||"Add photo"}</Text><Text style={s.uploadHelp}>PNG or JPG · image picker</Text></View></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Document attachment options" onPress={()=>setModal("document")} style={s.hit}><Text style={s.orangeLink}>Need to attach a document?</Text></Pressable><Label t="Priority"/><View style={s.priority}>{(["Normal","Urgent"] as const).map(x=><Pressable key={x} accessibilityRole="button" accessibilityLabel={`${x} priority`} accessibilityState={{selected:priority===x}} onPress={()=>setPriority(x)} style={[s.priorityButton,priority===x&&s.priorityOn]}><Text style={s.priorityText}>{x}</Text></Pressable>)}</View>{errors&&<Text accessibilityLiveRegion="polite" style={s.error}>Select a category and enter a subject and description within the displayed limits.</Text>}<Pressable accessibilityRole="button" accessibilityLabel="Submit Ticket" accessibilityState={{disabled:submitting}} disabled={submitting} onPress={submit} style={s.submit}><Text style={s.submitText}>{submitting?"Submitting…":"Submit Ticket"}</Text><Icon name="chevron" color="#fff" size={17}/></Pressable></View>
    <View style={[s.panel,s.chatPanel]}><Text style={s.panelTitle}>Live support</Text><View style={s.chatShell}><View style={s.chatHead}><View style={s.agentIcon}><Icon name="headset" color={C.ink} size={20}/></View><View style={s.flex}><Text style={s.chatTitle}>Karaa Support</Text><View style={s.row}><View style={s.greenDotSmall}/><Text style={s.chatOnline}>Online</Text></View></View><Pressable accessibilityRole="button" accessibilityLabel={chatMin?"Reopen live chat":"Minimise live chat"} accessibilityState={{expanded:!chatMin}} onPress={toggleChat} style={s.iconHit}><Icon name="minus" color={C.ink} size={17}/></Pressable></View>{!chatMin&&<><View style={s.chatBody}><Time t="10:42 AM"/><Bubble text="Hello Arjun, how can we help you today?"/><Time t="10:43 AM"/><Bubble mine text="I need help accessing a project document."/><Time t="10:44 AM"/><Bubble text="Of course. Please share the project name or document type."/>{messages.map((m,i)=><Bubble key={i} mine text={m}/>)}</View><View style={s.replyRow}><View style={s.greenDotSmall}/><Text style={s.reply}>Typically replies within 2 minutes</Text></View><View style={s.composer}><TextInput accessibilityLabel="Message" placeholder="Type your message" placeholderTextColor="#898b8e" value={message} onChangeText={setMessage} onSubmitEditing={send} style={s.message}/><Pressable accessibilityRole="button" accessibilityLabel={chatAttachment?`Chat attachment ${chatAttachment}`:"Attach photo to chat"} onPress={()=>pick("chat")} style={s.iconHit}><Icon name="clip" color={C.ink} size={17}/></Pressable>{!!message.trim()&&<Pressable accessibilityRole="button" accessibilityLabel="Send message" onPress={send} style={s.send}><Icon name="send" color="#fff" size={20}/></Pressable>}</View></>}</View></View>
   </View>
   {!!notice&&<Text accessibilityLiveRegion="polite" style={s.notice}>{notice}</Text>}
   <View style={s.historyHead}><View><Text style={s.sectionTitle}>Ticket history</Text><Text style={s.historySub}>Track your current and previous support requests.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="View all tickets" onPress={()=>setFilter("All")} style={s.hit}><Text style={s.orangeLink}>View all</Text><Icon name="chevron" size={15}/></Pressable></View><View style={s.filters}>{(["All","Open","Resolved"] as const).map(x=><Pressable key={x} accessibilityRole="button" accessibilityLabel={`Filter ${x} tickets`} accessibilityState={{selected:filter===x}} onPress={()=>setFilter(x)} style={[s.filter,filter===x&&s.filterOn]}><Text style={[s.filterText,filter===x&&s.filterTextOn]}>{x}</Text></Pressable>)}</View>
   <View style={s.ticketList}>{shown.map(t=><Pressable key={t.id} accessibilityRole="button" accessibilityLabel={`View ${t.subject}`} onPress={()=>{setSelected(t);setModal("ticket")}} style={s.ticket}><View style={[s.ticketIcon,t.status==="RESOLVED"&&s.ticketIconDone]}><Icon name={t.status==="RESOLVED"?"check":"clock"} color={t.status==="RESOLVED"?C.green:"#1264d8"} size={20}/></View><View style={s.ticketMain}><Text style={s.ticketId}>#{t.id}</Text><Text numberOfLines={1} style={s.ticketSubject}>{t.subject}</Text><Text numberOfLines={1} style={s.ticketMeta}>{t.context}</Text></View><View style={s.ticketDate}><Text style={s.date}>{t.date}</Text><Text style={s.updated}>{t.update}</Text></View><View style={s.ticketStatus}><Text style={[s.status,t.status==="RESOLVED"&&s.resolved]}>{t.status}</Text>{t.status==="IN REVIEW"&&<Text style={s.normal}>NORMAL</Text>}</View><Icon name="chevron" size={17}/></Pressable>)}</View>
   <View style={s.urgent}><View style={s.phoneBox}><Icon name="phone" color={C.ink} size={19}/></View><View style={s.flex}><Text style={s.urgentTitle}>Need urgent assistance?</Text><Text style={s.urgentText}>Call +91 120 450 7890</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Call now" onPress={()=>openUrl("tel:+911204507890")} style={s.call}><Text style={s.callText}>Call now</Text><Icon name="chevron" size={16}/></Pressable></View>
  </View>
  <Modal transparent visible={!!modal} animationType="fade" onRequestClose={()=>setModal(null)}><View style={s.scrim}><View style={s.modal}><Text style={s.modalTitle}>{modal==="hours"?"Service hours":modal==="category"?"Issue category":modal==="project"?"Related project":modal==="document"?"Document attachments":selected?.subject}</Text>{modal==="category"?<View>{["Documents","Payments & receipts","Project updates","Account & access"].map(v=><Pressable accessibilityRole="button" accessibilityLabel={`Choose ${v}`} key={v} onPress={()=>{setCategory(v);setModal(null)}} style={s.choice}><Text style={s.choiceText}>{v}</Text></Pressable>)}</View>:modal==="project"?<View>{projects.map(v=><Pressable accessibilityRole="button" accessibilityLabel={`Choose project ${v}`} key={v} onPress={()=>{setProject(v);setModal(null)}} style={s.choice}><Text style={s.choiceText}>{v}</Text></Pressable>)}</View>:<Text style={s.modalBody}>{modal==="hours"?"Live support: Monday–Saturday, 9:00 AM–6:00 PM IST. WhatsApp messages can be composed at any time.":modal==="document"?"This demo has no document picker installed, so PDF selection is not available. Add a PNG or JPG above, or describe the document in your request.":`${selected?.context} · ${selected?.date}\n${selected?.status} · ${selected?.update}`}</Text>}<Pressable accessibilityRole="button" accessibilityLabel="Close dialog" onPress={()=>setModal(null)} style={s.close}><Text style={s.closeText}>Close</Text></Pressable></View></View></Modal>
 </View>
}
function Metric({icon,n,l,last}:{icon:IconName;n:string;l:string;last?:boolean}){return <View style={[s.metric,last&&s.metricLast]}><Icon name={icon} color={C.gold} size={18}/><Text style={s.metricN}>{n}</Text><Text style={s.metricL}>{l}</Text></View>}
function Quick({icon,color,title,sub,online,onPress}:{icon:IconName;color?:string;title:string;sub:string;online?:boolean;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityLabel={title} onPress={onPress} style={s.quick}><Icon name={icon} color={color} size={25}/><Text style={s.quickTitle}>{title}</Text><Text style={s.quickSub}>{sub}</Text>{online&&<View style={s.onlineQuick}><View style={s.greenDotSmall}/><Text style={s.quickStatus}>Online</Text></View>}</Pressable>}
function Label({t}:{t:string}){return <Text style={s.label}>{t}</Text>}
function Select({label,value,onPress,muted,invalid}:{label:string;value:string;onPress:()=>void;muted?:boolean;invalid?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={label} hitSlop={{top:5,bottom:5}} onPress={onPress} style={[s.input,s.select,invalid&&s.invalid]}><Text numberOfLines={1} style={[s.selectText,muted&&s.muted]}>{value}</Text><View style={s.down}/></Pressable>}
function Time({t}:{t:string}){return <Text style={s.time}>{t}</Text>}
function Bubble({text,mine}:{text:string;mine?:boolean}){return <View style={[s.bubbleRow,mine&&s.bubbleMine]}>{!mine&&<View style={s.avatar}><Icon name="headset" color={C.ink} size={16}/></View>}<View style={[s.bubble,mine&&s.mine]}><Text style={s.bubbleText}>{text}</Text>{mine&&<Text style={s.ticks}>✓✓</Text>}</View></View>}
const s=StyleSheet.create({
 page:{backgroundColor:C.ivory,gap:0,marginHorizontal:-16,marginTop:-16},content:{paddingHorizontal:35,paddingBottom:8,gap:10},compatibility:{height:0,opacity:0,overflow:"hidden",position:"absolute"},compatHit:{minHeight:44},hero:{height:174,backgroundColor:"#f7f2e9",overflow:"hidden"},heroCopy:{paddingHorizontal:36,paddingTop:32,zIndex:3},eyebrow:{color:"#a66f13",fontSize:10,fontWeight:"700",letterSpacing:.7},heroTitle:{color:"#10110f",fontFamily:"serif",fontSize:39,lineHeight:45},heroSub:{color:"#5e6268",fontSize:11,lineHeight:18,marginTop:3},heroImage:{position:"absolute",right:-2,width:"54%",height:174,opacity:.78},heroFade:{position:"absolute",left:"39%",height:174,width:"31%",backgroundColor:"rgba(247,242,233,.68)"},
 overview:{backgroundColor:C.paper,borderColor:C.line,borderWidth:1,borderRadius:10,marginTop:-20,paddingHorizontal:14,paddingTop:14,shadowColor:"#000",shadowOpacity:.09,shadowRadius:10,shadowOffset:{width:0,height:5}},overline:{color:C.ink,fontFamily:"serif",fontSize:14,marginBottom:11},metrics:{flexDirection:"row"},metric:{alignItems:"center",flex:1,borderRightWidth:1,borderRightColor:C.line,paddingBottom:11},metricLast:{borderRightWidth:0},metricN:{fontFamily:"serif",color:C.ink,fontSize:25,lineHeight:30,marginTop:3},metricL:{color:C.muted,fontSize:9},online:{minHeight:59,borderTopWidth:1,borderTopColor:C.line,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},row:{flexDirection:"row",alignItems:"center"},greenDot:{width:8,height:8,borderRadius:4,backgroundColor:C.green,marginRight:7},greenDotSmall:{width:6,height:6,borderRadius:3,backgroundColor:C.green,marginRight:5},onlineText:{color:C.muted,fontSize:9},hit:{minHeight:44,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:6},orangeLink:{color:"#a66f13",fontSize:9},
 sectionTitle:{fontFamily:"serif",fontSize:20,color:"#111",lineHeight:25},quickRow:{flexDirection:"row",gap:10},quick:{minHeight:85,flex:1,borderWidth:1,borderColor:C.line,borderRadius:7,backgroundColor:C.paper,alignItems:"center",justifyContent:"center",padding:6},quickTitle:{fontSize:11,fontWeight:"600",color:"#181918",marginTop:5},quickSub:{fontSize:9,color:C.muted,marginTop:2},onlineQuick:{flexDirection:"row",alignItems:"center",marginTop:7},quickStatus:{fontSize:8,color:C.muted},
 twoCol:{flexDirection:"row",gap:8,alignItems:"stretch"},stacked:{flexDirection:"column"},panel:{flex:1,borderWidth:1,borderColor:C.line,borderRadius:7,backgroundColor:C.paper,padding:9},panelTitle:{fontFamily:"serif",fontSize:15,color:"#151615"},panelSub:{fontSize:8,color:C.muted,lineHeight:11,marginTop:1},label:{fontSize:7,color:"#292a29",marginTop:7,marginBottom:3},input:{minHeight:34,borderWidth:1,borderColor:C.line,borderRadius:5,backgroundColor:"#fff",fontSize:8,color:C.ink,paddingHorizontal:7},select:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},selectText:{fontSize:8,color:C.ink,flex:1},muted:{color:"#95969a"},down:{width:6,height:6,borderRightWidth:1,borderBottomWidth:1,borderColor:C.ink,transform:[{rotate:"45deg"}],marginRight:2,marginBottom:4},area:{height:62,paddingTop:8,textAlignVertical:"top"},invalid:{borderColor:"#b84336"},upload:{minHeight:44,borderWidth:1,borderColor:C.line,borderRadius:5,marginTop:7,flexDirection:"row",alignItems:"center",paddingHorizontal:8,gap:9},uploadTitle:{fontSize:8,color:C.ink},uploadHelp:{fontSize:7,color:"#8b8c90",marginTop:1},priority:{flexDirection:"row",gap:4},priorityButton:{minHeight:44,flex:1,borderWidth:1,borderColor:C.line,borderRadius:5,alignItems:"center",justifyContent:"center"},priorityOn:{borderColor:C.orange,backgroundColor:"#fffaf3"},priorityText:{fontSize:8,color:C.ink},error:{color:"#a9473c",fontSize:7,lineHeight:10,marginTop:4},submit:{minHeight:44,borderRadius:5,marginTop:8,backgroundColor:"#050505",flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:12},submitText:{color:"#fff",fontSize:9,fontWeight:"600"},
 chatPanel:{padding:8},chatShell:{borderWidth:1,borderColor:C.line,borderRadius:7,overflow:"hidden",marginTop:6,flex:1},chatHead:{height:45,backgroundColor:C.paper,flexDirection:"row",alignItems:"center",paddingLeft:7},agentIcon:{width:29,height:29,borderRadius:15,borderWidth:1,borderColor:C.line,alignItems:"center",justifyContent:"center",marginRight:7},flex:{flex:1},chatTitle:{color:C.ink,fontSize:9,fontWeight:"600"},chatOnline:{color:C.muted,fontSize:7},iconHit:{minWidth:44,minHeight:44,alignItems:"center",justifyContent:"center"},chatBody:{minHeight:248,padding:7},time:{fontSize:6,color:"#85878a",textAlign:"center",marginVertical:4},bubbleRow:{flexDirection:"row",alignItems:"center",marginBottom:3},bubbleMine:{justifyContent:"flex-end"},avatar:{width:23,height:23,borderRadius:12,backgroundColor:"#fbf4e8",alignItems:"center",justifyContent:"center",marginRight:5},bubble:{maxWidth:"78%",backgroundColor:"#f5f0e9",borderRadius:7,padding:7},mine:{backgroundColor:"#ffead0"},bubbleText:{fontSize:7.5,lineHeight:11,color:C.ink},ticks:{fontSize:6,textAlign:"right",marginTop:2},replyRow:{minHeight:31,flexDirection:"row",alignItems:"center",justifyContent:"center",borderTopWidth:1,borderTopColor:"#f2f0eb"},reply:{fontSize:6,color:C.muted},composer:{minHeight:49,borderTopWidth:1,borderTopColor:C.line,flexDirection:"row",alignItems:"center",paddingLeft:6},message:{minHeight:44,flex:1,fontSize:7},send:{minWidth:44,minHeight:44,borderRadius:22,backgroundColor:C.orange,alignItems:"center",justifyContent:"center",marginRight:3},notice:{backgroundColor:"#e5f0e7",color:"#3f7256",fontSize:8,padding:8},
 historyHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},historySub:{fontSize:8,color:C.muted},filters:{flexDirection:"row",gap:8},filter:{minHeight:44,minWidth:48,borderWidth:1,borderColor:C.line,borderRadius:5,alignItems:"center",justifyContent:"center",paddingHorizontal:12},filterOn:{borderColor:C.orange},filterText:{fontSize:7,color:C.muted},filterTextOn:{color:C.orange},ticketList:{gap:5},ticket:{minHeight:48,borderWidth:1,borderColor:C.line,borderRadius:6,backgroundColor:C.paper,flexDirection:"row",alignItems:"center",paddingHorizontal:7},ticketIcon:{width:32,height:32,borderRadius:5,backgroundColor:"#e7f0ff",alignItems:"center",justifyContent:"center",marginRight:7},ticketIconDone:{backgroundColor:"#e6f5e8"},ticketMain:{flex:1,minWidth:90},ticketId:{fontSize:7,color:C.muted},ticketSubject:{fontSize:8.5,color:C.ink,marginTop:1},ticketMeta:{fontSize:6.5,color:"#8a8b8e",marginTop:3},ticketDate:{width:74,alignItems:"center"},date:{fontSize:7,color:C.ink},updated:{fontSize:6,color:C.muted,marginTop:9},ticketStatus:{width:51,alignItems:"flex-start"},status:{fontSize:6,color:"#175ab5",borderWidth:1,borderColor:"#aad0ff",backgroundColor:"#eff6ff",borderRadius:3,padding:3},resolved:{color:"#19832e",borderColor:"#a9dcb1",backgroundColor:"#eaf7eb"},normal:{fontSize:6,color:C.muted,borderWidth:1,borderColor:C.line,backgroundColor:"#f4f4f3",borderRadius:3,padding:3,marginTop:4},urgent:{minHeight:50,borderWidth:1,borderColor:"#f2d7b4",borderRadius:6,backgroundColor:"#fff8ef",flexDirection:"row",alignItems:"center",paddingHorizontal:10},phoneBox:{width:29,height:29,borderRadius:5,backgroundColor:"#ffe9c8",alignItems:"center",justifyContent:"center",marginRight:9},urgentTitle:{fontSize:8,color:C.ink},urgentText:{fontSize:7,color:C.muted,marginTop:2},call:{minHeight:44,flexDirection:"row",alignItems:"center",gap:7},callText:{fontSize:8,color:C.orange},
 scrim:{flex:1,backgroundColor:"rgba(0,0,0,.55)",alignItems:"center",justifyContent:"center",padding:25},modal:{width:"100%",maxWidth:340,backgroundColor:C.ivory,padding:20,borderRadius:8},modalTitle:{fontFamily:"serif",fontSize:18,color:C.ink},modalBody:{fontSize:12,lineHeight:19,color:C.muted,marginVertical:12},choice:{minHeight:44,borderBottomWidth:1,borderBottomColor:C.line,justifyContent:"center"},choiceText:{fontSize:12,color:C.ink},close:{minHeight:44,backgroundColor:C.ink,alignItems:"center",justifyContent:"center",marginTop:12},closeText:{color:"#fff",fontWeight:"700"}
});
const ic=StyleSheet.create({circle:{borderWidth:1.5,borderRadius:99,alignItems:"center",justifyContent:"center"},checkA:{position:"absolute",width:6,height:1.5,transform:[{rotate:"45deg"}],left:4,top:11},checkB:{position:"absolute",width:10,height:1.5,transform:[{rotate:"-48deg"}],left:8,top:9},clockA:{position:"absolute",width:1.5,height:7,top:3,left:9},clockB:{position:"absolute",width:6,height:1.5,top:10,left:9,transform:[{rotate:"35deg"}]},chat:{position:"relative"},chatA:{position:"absolute",left:0,top:1,width:"72%",height:"65%",borderWidth:1.5,borderRadius:4},chatB:{position:"absolute",right:0,bottom:1,width:"62%",height:"57%",borderWidth:1.5,borderRadius:4},phoneMini:{width:9,height:14,borderLeftWidth:2,borderBottomWidth:2,borderRadius:5,transform:[{rotate:"-36deg"}]},ticket:{borderWidth:1.5,borderRadius:2,justifyContent:"center",paddingHorizontal:4},rule:{height:1.5,width:"70%"},rule2:{marginTop:5,width:"90%"},headset:{borderWidth:1.5,borderBottomWidth:0,borderTopLeftRadius:99,borderTopRightRadius:99,marginTop:3},mic:{position:"absolute",right:-2,bottom:1,width:5,height:7,borderRightWidth:1.5,borderBottomWidth:1.5,borderRadius:3},clipFrame:{alignItems:"center",justifyContent:"center"},clipOuter:{width:9,height:15,borderWidth:1.5,borderRadius:6,transform:[{rotate:"28deg"}],alignItems:"center",justifyContent:"center"},clipInner:{width:4,height:10,borderWidth:1,borderTopWidth:0,borderRadius:3},send:{width:"65%",height:"65%",borderTopWidth:1.5,borderRightWidth:1.5,transform:[{rotate:"45deg"}],alignSelf:"center",marginTop:4},phone:{width:"50%",height:"90%",borderLeftWidth:2,borderBottomWidth:2,borderRadius:5,transform:[{rotate:"-38deg"}],alignSelf:"center"},minus:{height:1,width:"75%",marginTop:"50%",alignSelf:"center"},arrow:{justifyContent:"center"},arrowLine:{height:1,width:"75%"},arrowHead:{position:"absolute",right:1,width:"45%",height:"45%",borderTopWidth:1,borderRightWidth:1,transform:[{rotate:"45deg"}]}});
