import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

export type LiveMapProject = { name: string; place: string; checked: string; teams: string; tone: string };
type Person = { initials: string; name: string; role: string; id: string };

const AAROHAN_PERSON: Person = { initials: 'RM', name: 'Rohan Mehta', role: 'Project Manager', id: 'EMP-KG-0243' };

export function LiveWorkforceMap({ project, onBack }: { project: LiveMapProject; onBack: () => void }) {
  const person = useMemo<Person>(() => project.name === 'Aarohan Medical City'
    ? AAROHAN_PERSON
    : { initials: project.name.split(' ').slice(0, 2).map(word => word[0]).join(''), name: `${project.name.split(' ')[0]} Site Lead`, role: 'Site Manager', id: `EMP-KG-${project.checked.padStart(4, '0')}` }, [project]);
  const [filter, setFilter] = useState('All Personnel');
  const [notice, setNotice] = useState('');
  const [zoom, setZoom] = useState(14);
  const [selected, setSelected] = useState(person.name);
  const act = (message: string) => setNotice(`${message} · Prototype preview only — no GPS or live backend is connected.`);
  const IconButton = ({ name, glyph, onPress }: { name: string; glyph: string; onPress: () => void }) => (
    <Pressable accessibilityRole="button" accessibilityLabel={name} onPress={onPress} style={styles.iconButton}><Text style={styles.iconGlyph}>{glyph}</Text></Pressable>
  );
  const alertCount = project.tone === 'danger' ? '03' : project.tone === 'warn' ? '01' : '01';

  return <View style={styles.page} testID="live-workforce-map">
    <View style={styles.header}>
      <Pressable accessibilityRole="button" accessibilityLabel="Back to Geo Location" onPress={onBack} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable>
      <View style={styles.flex}><Text style={styles.eyebrow}>LIVE WORKFORCE MAP</Text><Text numberOfLines={1} style={styles.title}>{project.name}</Text><Text style={styles.headerPlace}>⌖ {project.place}</Text></View>
      <View style={styles.liveBlock}><Text style={styles.live}>● LIVE</Text><Text style={styles.headerMeta}>Updated just now</Text></View>
      <IconButton name="Refresh workforce map" glyph="↻" onPress={() => act('Bundled map data refreshed')} />
      <IconButton name="Map layers" glyph="▱" onPress={() => act('Layer chooser opened')} />
    </View>
    {notice ? <Pressable accessibilityRole="button" accessibilityLabel="Dismiss map notice" onPress={() => setNotice('')} style={styles.notice}><Text numberOfLines={2} style={styles.noticeText}>{notice}</Text></Pressable> : null}

    <View style={styles.controlBar}>
      {['All Personnel', 'Field Teams', 'Managers', 'Alerts'].map(item => <Pressable key={item} accessibilityRole="tab" accessibilityLabel={item} accessibilityState={{ selected: filter === item }} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.filterSelected]}><Text numberOfLines={1} style={[styles.filterText, filter === item && styles.filterTextSelected]}>{item}</Text></Pressable>)}
      <View style={styles.search}><Text style={styles.controlGlyph}>⌕</Text><TextInput accessibilityLabel="Search map personnel" placeholder="Search" onChangeText={query => query.toLowerCase().includes(person.name.split(' ')[0].toLowerCase()) && setSelected(person.name)} style={styles.searchInput} /></View>
      <Pressable accessibilityRole="button" accessibilityLabel="Change map time" onPress={() => act('Time selector opened')} style={styles.time}><Text numberOfLines={1} style={styles.timeText}>▣ Today · 10:42 AM⌄</Text></Pressable>
    </View>

    <View accessibilityRole="image" accessibilityLabel={`Static site map for ${project.name}`} style={styles.map}>
      <View style={[styles.road, { top: 35, transform: [{ rotate: '8deg' }] }]} /><View style={[styles.road, { top: 167, transform: [{ rotate: '-12deg' }] }]} />
      <View style={[styles.roadVertical, { left: 92, transform: [{ rotate: '15deg' }] }]} /><View style={[styles.roadVertical, { left: 270, transform: [{ rotate: '-8deg' }] }]} />
      <Text style={[styles.mapLabel, { left: 13, top: 13 }]}>University Road</Text><Text style={[styles.mapLabel, { left: 162, top: 76 }]}>Clinical{`\n`}Block</Text><Text style={[styles.mapLabel, { left: 236, top: 119 }]}>East{`\n`}Wing</Text><Text style={[styles.mapLabel, { left: 53, top: 189 }]}>Gate A</Text>
      <View style={styles.geofence}><Text style={styles.geofenceText}>AUTHORISED GEOFENCE</Text></View>
      {[['24', 56, 51, '#29944C'], ['12', 253, 50, '#29944C'], ['38', 180, 185, '#29944C'], ['!', 33, 139, '#D94434']].map(([text, left, top, color]) => <Pressable key={`${left}`} accessibilityRole="button" accessibilityLabel={`Select map marker ${text}`} onPress={() => setSelected(person.name)} style={[styles.marker, { left: left as number, top: top as number, backgroundColor: color as string }]}><Text style={styles.markerText}>{text}</Text></Pressable>)}
      <Pressable accessibilityRole="button" accessibilityLabel={`Select ${person.name}`} accessibilityState={{ selected: selected === person.name }} onPress={() => setSelected(person.name)} style={styles.personPin}><Text style={styles.pinInitials}>{person.initials}</Text><Text style={styles.pinName}>{person.name}</Text></Pressable>
      <View style={styles.compass}><Text style={styles.compassArrow}>↑</Text><Text style={styles.micro}>N</Text></View>
      <View style={styles.zoom}><IconButton name="Zoom in" glyph="+" onPress={() => setZoom(value => value + 1)} /><IconButton name="Zoom out" glyph="−" onPress={() => setZoom(value => Math.max(1, value - 1))} /></View>
      <Pressable accessibilityRole="button" accessibilityLabel="Recenter map" onPress={() => act(`Map recentered at zoom ${zoom}`)} style={styles.recenter}><Text>◎</Text></Pressable>
      <Pressable accessibilityRole="button" accessibilityLabel="Open mini map layers" onPress={() => act('Mini-map layers opened')} style={styles.miniMap}><View style={styles.miniRoad} /><Text>▱</Text></Pressable>
      <View style={styles.legend}>{[['#29944C', 'Live'], ['#B57B0A', 'Manager'], ['#E09A18', 'Near boundary'], ['#D64335', 'Outside geofence'], ['#888', 'Offline']].map(([color, label]) => <View key={label} style={styles.legendItem}><View style={[styles.dot, { backgroundColor: color }]} /><Text style={styles.legendText}>{label}</Text></View>)}</View>
    </View>

    <View style={styles.metrics}>{[[project.checked, 'Checked in'], [project.teams, 'Field teams'], [alertCount, 'Alert'], ['✓', 'All systems live']].map(([value, label]) => <View key={label} style={styles.metric}><Text style={[styles.metricValue, label === 'Alert' && styles.danger]}>{value}</Text><Text style={styles.micro}>{label}</Text></View>)}</View>

    <View style={styles.sheet}>
      <View style={styles.handle} />
      <View style={styles.person}><Text style={styles.avatar}>{person.initials}</Text><View style={styles.flex}><Text style={styles.personName}>{person.name}</Text><Text style={styles.muted}>{person.role}</Text><Text style={styles.onSite}>● On Site · Live</Text><Text style={styles.micro}>{person.id}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`Message ${person.name}`} onPress={() => act(`Message composer for ${person.name} opened`)} style={styles.messageIcon}><Text style={styles.gold}>▢</Text><Text style={styles.microGold}>Message</Text></Pressable></View>
      <View style={styles.fourStats}>{[['08:12 AM', 'Checked in'], ['06:30 PM', 'Expected checkout'], ['10:41 AM', 'Last location update'], ['8h 18m', 'Time on site']].map(([value, label]) => <View key={label} style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text numberOfLines={1} style={styles.micro}>{label}</Text></View>)}</View>
      <View style={styles.detailRow}>
        <View style={styles.detailCard}><Text style={styles.section}>CURRENT ASSIGNMENT</Text><Text style={styles.strong}>Structural frame inspection</Text><Text style={styles.muted}>Clinical Block · Level 8</Text><Text style={styles.progress}>IN PROGRESS</Text></View>
        <View style={styles.detailCard}><Text style={styles.section}>CURRENT LOCATION</Text><Text style={styles.strong}>Clinical Block · East Wing</Text><Text style={styles.muted}>Accuracy ± 6m</Text><Text style={styles.onSite}>♡ Within authorised zone</Text></View>
      </View>
      <View style={styles.movement}><Text style={styles.muted}>♧ Last movement  <Text style={styles.strong}>2 min ago</Text></Text><Text style={styles.muted}>⌁ 184m travelled today</Text></View>
      <View style={styles.timeline}>{[['08:12', 'Check in'], ['09:05', 'Gate A'], ['10:18', 'Clinical Block'], ['10:41', 'East Wing']].map(([time, label]) => <Pressable key={time} accessibilityRole="button" accessibilityLabel={`Open movement ${time} ${label}`} onPress={() => act(`Movement at ${time} opened`)} style={styles.timelineItem}><Text style={styles.timelineTime}>{time}</Text><View style={styles.timelineDot} /><Text style={styles.micro}>{label}</Text></Pressable>)}</View>
      <View style={styles.actions}><Pressable accessibilityRole="button" accessibilityLabel="View full activity" onPress={() => act('Full activity timeline opened')} style={styles.secondary}><Text style={styles.actionText}>⌁ View full activity</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Send message to ${person.name}`} onPress={() => act(`Message composer for ${person.name} opened`)} style={styles.primary}><Text style={styles.primaryText}>▢ Message</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="More employee actions" onPress={() => act('Employee actions menu opened')} style={styles.more}><Text>•••</Text></Pressable></View>
      <Pressable accessibilityRole="button" accessibilityLabel={`View all ${project.checked} people`} onPress={() => act(`People directory for ${project.name} opened`)} style={styles.people}><Text style={styles.actionText}>♧  View all {project.checked} people →</Text></Pressable>
    </View>
  </View>;
}

const styles = StyleSheet.create({
  page: { backgroundColor: '#F7F4EC', marginHorizontal: -16, marginTop: -16 }, flex: { flex: 1 },
  header: { alignItems: 'center', backgroundColor: '#161817', flexDirection: 'row', minHeight: 60, paddingHorizontal: 4 }, back: { alignItems: 'center', justifyContent: 'center', minHeight: 44, minWidth: 44 }, backText: { color: '#FFF', fontSize: 29 },
  eyebrow: { color: '#C89125', fontSize: 7, fontWeight: '900', letterSpacing: .8 }, title: { color: '#FFF', fontFamily: 'serif', fontSize: 14, fontWeight: '800' }, headerPlace: { color: '#B9B5AC', fontSize: 7 }, liveBlock: { alignItems: 'flex-end', paddingHorizontal: 3 }, live: { color: '#4CB569', fontSize: 8, fontWeight: '900' }, headerMeta: { color: '#AAA69E', fontSize: 6 },
  iconButton: { alignItems: 'center', justifyContent: 'center', minHeight: 44, minWidth: 44 }, iconGlyph: { fontSize: 17 }, notice: { backgroundColor: '#FFF0CF', borderLeftColor: '#B57B0A', borderLeftWidth: 3, justifyContent: 'center', minHeight: 44, paddingHorizontal: 7 }, noticeText: { color: '#5A4518', fontSize: 8 },
  controlBar: { alignItems: 'center', backgroundColor: '#FFF', flexDirection: 'row', minHeight: 48, paddingHorizontal: 4 }, filter: { alignItems: 'center', borderColor: '#DDD7CB', borderRadius: 2, borderWidth: 1, justifyContent: 'center', minHeight: 44, paddingHorizontal: 4 }, filterSelected: { backgroundColor: '#FFF3D7', borderColor: '#C58A17' }, filterText: { color: '#66625B', fontSize: 6.5, fontWeight: '800' }, filterTextSelected: { color: '#9B6809' }, search: { alignItems: 'center', flexDirection: 'row', height: 44, marginLeft: 'auto', width: 45 }, controlGlyph: { fontSize: 13 }, searchInput: { flex: 1, fontSize: 7, paddingHorizontal: 2 }, time: { alignItems: 'center', justifyContent: 'center', minHeight: 44, paddingHorizontal: 3, width: 84 }, timeText: { color: '#383630', fontSize: 6.5, fontWeight: '800' },
  map: { backgroundColor: '#E7E1D3', height: 250, overflow: 'hidden', position: 'relative' }, road: { backgroundColor: '#FBFAF4', borderColor: '#D7D1C4', borderWidth: 1, height: 25, left: -20, position: 'absolute', width: 450 }, roadVertical: { backgroundColor: '#FBFAF4', height: 290, position: 'absolute', top: -20, width: 21 }, mapLabel: { color: '#777166', fontSize: 7, position: 'absolute', textAlign: 'center' }, geofence: { backgroundColor: 'rgba(225,159,28,.13)', borderColor: '#D59312', borderStyle: 'dashed', borderWidth: 2, height: 155, left: 78, position: 'absolute', top: 42, transform: [{ rotate: '-5deg' }], width: 218 }, geofenceText: { color: '#9C6D10', fontSize: 6, fontWeight: '900', margin: 4 },
  marker: { alignItems: 'center', borderColor: '#FFF', borderRadius: 15, borderWidth: 2, height: 30, justifyContent: 'center', position: 'absolute', width: 30 }, markerText: { color: '#FFF', fontSize: 8, fontWeight: '900' }, personPin: { alignItems: 'center', left: 166, position: 'absolute', top: 90 }, pinInitials: { backgroundColor: '#A87510', borderColor: '#FFF', borderRadius: 18, borderWidth: 3, color: '#FFF', fontSize: 8, fontWeight: '900', height: 36, lineHeight: 30, textAlign: 'center', width: 36 }, pinName: { backgroundColor: '#FFF', borderRadius: 2, color: '#38352E', fontSize: 6.5, fontWeight: '800', padding: 3 }, compass: { alignItems: 'center', backgroundColor: '#FFF', borderRadius: 20, padding: 6, position: 'absolute', right: 7, top: 6 }, compassArrow: { color: '#D94837' }, zoom: { backgroundColor: '#FFF', position: 'absolute', right: 7, top: 55 }, recenter: { alignItems: 'center', backgroundColor: '#FFF', borderRadius: 3, height: 44, justifyContent: 'center', position: 'absolute', right: 7, top: 146, width: 44 }, miniMap: { alignItems: 'center', backgroundColor: '#EEE7D8', borderColor: '#FFF', borderWidth: 2, bottom: 7, height: 44, justifyContent: 'center', position: 'absolute', right: 7, width: 52 }, miniRoad: { backgroundColor: '#FFF', height: 5, position: 'absolute', transform: [{ rotate: '25deg' }], width: 58 },
  legend: { backgroundColor: 'rgba(255,255,255,.94)', bottom: 6, left: 7, padding: 5, position: 'absolute' }, legendItem: { alignItems: 'center', flexDirection: 'row', gap: 3, minHeight: 14 }, dot: { borderRadius: 4, height: 7, width: 7 }, legendText: { color: '#55524C', fontSize: 6 },
  metrics: { backgroundColor: '#FFF', flexDirection: 'row', minHeight: 50 }, metric: { alignItems: 'center', borderRightColor: '#E2DDD4', borderRightWidth: 1, flex: 1, justifyContent: 'center' }, metricValue: { color: '#36964C', fontFamily: 'serif', fontSize: 14, fontWeight: '900' }, danger: { color: '#D65140' }, micro: { color: '#77736B', fontSize: 6.5, lineHeight: 9 },
  sheet: { backgroundColor: '#FFF', borderTopLeftRadius: 16, borderTopRightRadius: 16, marginTop: -1, paddingHorizontal: 10 }, handle: { alignSelf: 'center', backgroundColor: '#C7C2B9', borderRadius: 3, height: 4, marginVertical: 5, width: 38 }, person: { alignItems: 'center', borderBottomColor: '#E3DED5', borderBottomWidth: 1, flexDirection: 'row', gap: 8, paddingBottom: 5 }, avatar: { backgroundColor: '#F3EEE3', borderRadius: 20, color: '#80643A', fontSize: 10, fontWeight: '900', height: 40, lineHeight: 40, textAlign: 'center', width: 40 }, personName: { color: '#22211D', fontFamily: 'serif', fontSize: 13, fontWeight: '900' }, muted: { color: '#716E67', fontSize: 7, lineHeight: 10 }, onSite: { color: '#37944B', fontSize: 6.5, fontWeight: '800' }, messageIcon: { alignItems: 'center', justifyContent: 'center', minHeight: 44, minWidth: 54 }, gold: { color: '#B77A09', fontSize: 16 }, microGold: { color: '#A76F08', fontSize: 6.5, fontWeight: '900' },
  fourStats: { borderBottomColor: '#E5E0D8', borderBottomWidth: 1, flexDirection: 'row' }, stat: { alignItems: 'center', flex: 1, justifyContent: 'center', minHeight: 44 }, statValue: { color: '#282620', fontFamily: 'serif', fontSize: 9, fontWeight: '900' }, detailRow: { flexDirection: 'row', gap: 6, paddingVertical: 5 }, detailCard: { borderColor: '#EEEAE3', borderRadius: 3, borderWidth: 1, flex: 1, minHeight: 65, padding: 5 }, section: { color: '#987020', fontSize: 6, fontWeight: '900', letterSpacing: .45 }, strong: { color: '#282620', fontSize: 7.5, fontWeight: '900' }, progress: { alignSelf: 'flex-start', backgroundColor: '#E7F4E5', color: '#378C46', fontSize: 5.5, fontWeight: '900', marginTop: 3, padding: 2 },
  movement: { borderBottomColor: '#E5E0D8', borderTopColor: '#E5E0D8', borderTopWidth: 1, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 32, paddingVertical: 6 }, timeline: { flexDirection: 'row', justifyContent: 'space-between' }, timelineItem: { alignItems: 'center', justifyContent: 'center', minHeight: 44, minWidth: 56 }, timelineTime: { color: '#66625B', fontSize: 6.5, fontWeight: '800' }, timelineDot: { backgroundColor: '#C68B16', borderRadius: 4, height: 6, marginVertical: 2, width: 6 },
  actions: { flexDirection: 'row', gap: 5 }, secondary: { alignItems: 'center', borderColor: '#BDB7AD', borderRadius: 3, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 44 }, primary: { alignItems: 'center', backgroundColor: '#D99009', borderRadius: 3, flex: 1, justifyContent: 'center', minHeight: 44 }, more: { alignItems: 'center', borderColor: '#D8D2C8', borderRadius: 3, borderWidth: 1, justifyContent: 'center', minHeight: 44, minWidth: 44 }, actionText: { color: '#3B3933', fontSize: 7, fontWeight: '800' }, primaryText: { color: '#FFF', fontSize: 7.5, fontWeight: '900' }, people: { alignItems: 'center', borderColor: '#EEEAE3', borderRadius: 3, borderWidth: 1, justifyContent: 'center', marginVertical: 5, minHeight: 44 },
});
