import { useState } from "react";
import type React from "react";
import { Image, Modal, Pressable, StyleSheet, Switch, Text, View } from "react-native";
import type { ImageSourcePropType } from "react-native";
import type { OfflineDemoAction, OfflineDemoState } from "./offline-demo";
import type { PortfolioProject, SubverticalPortfolio } from "./subvertical-projects";

const photos: ImageSourcePropType[] = [
  require("../../assets/demo/amaravati-structure.webp"),
  require("../../assets/demo/amaravati-structure-progress.webp"),
  require("../../assets/demo/amaravati-pour.webp"),
];
export const projectDetailTabs = ["timeline", "overview", "documents", "media"] as const;
export const projectTimelineFilters = ["All updates", "Milestones", "Site Updates", "Documents"] as const;
export type TimelineVariant = "current" | "foundation" | "site" | "mobilisation" | "approvals" | "upcoming";
export type TimelineItem = { variant: TimelineVariant; title: string; date: string; status: string; detail: string; filters: readonly string[] };
export const aarohanTimeline: readonly TimelineItem[] = [
  { variant: "current", date: "18 AUG 2026", status: "IN PROGRESS", title: "Structural frame reaches Level 8", detail: "The main clinical block has reached Level 8. Core structural work remains on schedule, with the next wing slab now underway.", filters: ["Milestones", "Site Updates"] },
  { variant: "foundation", date: "01 JUL 2026", status: "COMPLETE", title: "Foundation works completed", detail: "Pile foundations, raft works and substructure quality checks have been completed and verified.", filters: ["Milestones"] },
  { variant: "site", date: "14 MAR 2026", status: "SITE UPDATE", title: "Basement and services core underway", detail: "Basement retaining works and the central services core progressed across the active work fronts.", filters: ["Site Updates"] },
  { variant: "mobilisation", date: "10 NOV 2025", status: "COMPLETE", title: "Site mobilisation completed", detail: "Temporary services, welfare areas, material routes and perimeter controls were fully commissioned.", filters: ["Milestones", "Documents"] },
  { variant: "approvals", date: "20 AUG 2025", status: "COMPLETE", title: "Planning and statutory approvals", detail: "Planning consent and statutory approvals were recorded for the approved development programme.", filters: ["Documents"] },
  { variant: "upcoming", date: "Q2 2027", status: "UPCOMING", title: "Building envelope", detail: "Façade installation, weatherproofing and external envelope works.", filters: ["Milestones"] },
] as const;

type IconName = "timeline" | "overview" | "documents" | "media" | "location" | "photo" | "file" | "shield" | "bell";
function Icon({ name, gold = false }: { name: IconName; gold?: boolean }) {
  const marks: Record<IconName, string> = { timeline: "◴", overview: "▣", documents: "▤", media: "▧", location: "⌖", photo: "▧", file: "▤", shield: "♢", bell: "♧" };
  return <Text style={[s.icon, gold && s.gold]}>{marks[name]}</Text>;
}

export function PortfolioProjectDetail({ project, portfolio, selectedTab, onAction }: { project: PortfolioProject; portfolio: SubverticalPortfolio; selectedTab: OfflineDemoState["selectedProjectDetailTab"]; onAction: (action: OfflineDemoAction) => void }): React.ReactElement {
  const [filter, setFilter] = useState<(typeof projectTimelineFilters)[number]>("All updates");
  const [notify, setNotify] = useState(true);
  const [preview, setPreview] = useState<string | null>(null);
  const photoNumber = preview?.match(/photo (\d+)/i)?.[1];
  const previewPhoto = photoNumber ? photos[(Number(photoNumber) - 1) % photos.length] : photos[0];
  const aarohan = project.id === "aarohan-medical-city-pune";
  const timeline = aarohan ? aarohanTimeline : aarohanTimeline.map((item, index) => index ? item : { ...item, title: `${project.currentMilestone} reaches the next delivery stage`, detail: `${project.name} has advanced through ${project.currentMilestone.toLowerCase()}. Delivery remains coordinated across the active site.` });
  return <View style={s.page} testID={`project-detail-${project.id}`}>
    <ProjectSummary project={project} portfolio={portfolio} onBack={() => onAction({ type: "return-to-subvertical" })} />
    <View accessibilityRole="tablist" style={s.tabs} testID="project-primary-tabs">
      {projectDetailTabs.map(tab => <Pressable accessibilityRole="tab" accessibilityLabel={cap(tab)} accessibilityState={{ selected: selectedTab === tab }} key={tab} onPress={() => onAction({ type: "select-project-detail-tab", tab })} style={[s.tab, selectedTab === tab && s.tabOn]}>
        <Icon name={tab} gold={selectedTab === tab} /><Text style={[s.tabText, selectedTab === tab && s.gold]}>{cap(tab)}</Text>
      </Pressable>)}
    </View>
    {selectedTab === "timeline" && <View style={s.body}>
      <View style={s.filters} testID="timeline-filter-row">{projectTimelineFilters.map(item => <Pressable accessibilityRole="button" accessibilityLabel={`Filter ${item}`} key={item} onPress={() => setFilter(item)} style={[s.chip, filter === item && s.chipOn]}><Text numberOfLines={1} style={[s.chipText, filter === item && s.gold]}>{item}</Text></Pressable>)}</View>
      <Text style={s.heading}>Project Timeline</Text>
      <Text style={s.intro}>Follow every milestone, update and verified site record.</Text>
      <View style={s.timeline} testID="timeline-list">{timeline.filter(item => filter === "All updates" || item.filters.includes(filter)).map((item, index, visible) => <TimelineEntry key={item.variant} item={item} last={index === visible.length - 1} onPreview={setPreview} />)}</View>
      <View style={s.next} testID="next-milestone-bar"><View style={s.nextBell}><Icon name="bell" gold /></View><View style={s.nextCopy}><Text style={s.nextLabel}>NEXT MAJOR MILESTONE</Text><Text style={s.nextTitle}>Building envelope</Text><Text style={s.muted}>Expected Q2 2027</Text></View><View style={s.notify}><Text style={s.notifyText}>Notify me</Text><Switch accessibilityLabel="Notify me" style={s.notifySwitch} value={notify} onValueChange={setNotify} trackColor={{ true: GOLD, false: "#D8D3C9" }} thumbColor="#FFF" /></View></View>
    </View>}
    {selectedTab === "overview" && <View style={s.body}><Text style={s.heading}>Project Overview</Text><Fact label="Development" value={portfolio.title} /><Fact label="Location" value={project.location} /><Fact label="Current delivery" value={`${project.progress}% complete · ${project.status}`} /><Fact label="Opening" value={String(project.openingYear)} /><Fact label="Scope" value="A coordinated destination combining resilient infrastructure, public realm and operationally ready facilities." /></View>}
    {selectedTab === "documents" && <View style={s.body}><Text style={s.heading}>Project Documents</Text>{["Site Report · 18 Aug 2026", "Foundation QA Report", "Planning Approval Record"].map(x => <Action key={x} label={`Preview ${x}`} onPress={() => setPreview(x)} text={x} icon="file" />)}</View>}
    {selectedTab === "media" && <View style={s.body}><Text style={s.heading}>Project Media</Text><Text style={s.intro}>Eight local prototype site photographs</Text><View style={s.grid}>{[...photos, ...photos, photos[0], photos[1]].map((p, i) => <Pressable accessibilityLabel={`Open project photo ${i + 1}`} key={i} onPress={() => setPreview(`Project photo ${i + 1}`)} style={s.gridItem}><Image accessibilityLabel={`Prototype project photo ${i + 1}`} resizeMode="cover" source={p} style={s.gridPhoto} /></Pressable>)}</View></View>}
    <PreviewModal preview={preview} photo={previewPhoto} close={() => setPreview(null)} />
  </View>;
}

function ProjectSummary({ project, portfolio, onBack }: { project: PortfolioProject; portfolio: SubverticalPortfolio; onBack: () => void }) {
  return <View style={s.summary} testID="project-summary"><Pressable accessibilityRole="button" accessibilityLabel={`Back to ${portfolio.title}`} onPress={onBack}><Text style={s.eyebrow}>{portfolio.title.toUpperCase()} / PROJECT 01</Text></Pressable><View style={s.summaryTop}><Image accessibilityLabel={`${project.name} project site`} resizeMode="cover" source={project.image} style={s.hero} /><View style={s.summaryCopy}><Text style={s.name}>{project.name}</Text><Text style={s.location}><Icon name="location" /> {project.location}</Text><Text style={s.status}>●  {project.status.toUpperCase()}</Text></View></View><View style={s.metrics}><Metric big={`${project.progress}%`} label="Complete" /><Metric big={String(project.openingYear)} label="Opening" /><Metric big="18 Aug 2026" label="Last updated" small /></View><View accessibilityLabel={`${project.progress}% progress`} style={s.progressRow}><View style={s.rail}><View style={[s.fill, { width: `${project.progress}%` }]} /></View></View></View>;
}
function Metric({ big, label, small = false }: { big: string; label: string; small?: boolean }) { return <View style={s.metric}><Text style={[s.metricBig, small && s.metricDate]}>{big}</Text><Text style={s.metricLabel}>{label}</Text></View>; }
function TimelineEntry({ item, last, onPreview }: { item: TimelineItem; last: boolean; onPreview: (x: string) => void }) {
  const completed = item.variant !== "current" && item.variant !== "upcoming";
  return <View style={s.timelineRow} testID={`timeline-variant-${item.variant}`}><View style={[s.line, last && s.lineLast, item.variant === "upcoming" && s.lineFuture]} /><View style={[s.node, completed && s.nodeDone, item.variant === "current" && s.nodeCurrent, item.variant === "upcoming" && s.nodeUpcoming]}>{completed && <Text style={s.tick}>✓</Text>}{item.variant === "current" && <View style={s.nodeCore} />}</View><View style={[s.event, item.variant === "current" && s.featured]}><CardCopy item={item} />{item.variant === "current" && <CurrentMedia onPreview={onPreview} />}{item.variant === "foundation" && <SplitMedia onPreview={onPreview} count={2} more="+3" />}{item.variant === "site" && <SingleMedia onPreview={onPreview} />}{item.variant === "mobilisation" && <View style={s.actions}><Action label="Preview Mobilisation Report" text="Mobilisation Report.pdf" icon="file" onPress={() => onPreview("Mobilisation Report.pdf")} /><Action label="Preview Safety Plan" text="Safety Plan.pdf" icon="file" onPress={() => onPreview("Safety Plan.pdf")} /></View>}{item.variant === "approvals" && <View style={s.statusPanel}><Text style={s.approved}>✓  Approved</Text><Text style={s.onSchedule}>□  On schedule</Text></View>}{item.variant === "upcoming" && <Text style={s.planned}>Planned start · Q2 2027</Text>}</View></View>;
}
function CardCopy({ item }: { item: TimelineItem }) {
  const hasSideMedia = item.variant === "foundation" || item.variant === "site";
  return <View style={[item.variant === "approvals" && s.approvalCopy, hasSideMedia && s.sideMediaCopy]}><View style={s.meta}><Text style={s.date}>{item.date}</Text><Text style={[s.badge, item.variant === "upcoming" && s.badgeUpcoming]}>{item.status}</Text></View><Text style={s.eventTitle}>{item.title}</Text><Text style={s.detail}>{item.detail}</Text></View>;
}
function Thumb({ index, more, onPreview }: { index: number; more?: string; onPreview: (x: string) => void }) { return <Pressable accessibilityLabel={`Open timeline photo ${index + 1}`} onPress={() => onPreview(`Project photo ${index + 1}`)} style={s.thumbTarget}><Image source={photos[index % photos.length]} resizeMode="cover" style={s.photo} />{more && <View style={s.moreShade}><Text style={s.more}>{more}</Text></View>}</Pressable>; }
function CurrentMedia({ onPreview }: { onPreview: (x: string) => void }) { return <><View style={s.gallery}><Thumb index={0} onPreview={onPreview} /><Thumb index={1} onPreview={onPreview} /><Thumb index={2} more="+5" onPreview={onPreview} /></View><View style={s.actions}><Action label="View 8 Photos" text="View 8 photos" icon="photo" onPress={() => onPreview("Project photo gallery")} /><Action label="Preview Site Report PDF" text="Site report.pdf · 2.4 MB" icon="file" onPress={() => onPreview("Site Report PDF")} /></View><Text style={s.verified}><Icon name="shield" gold /> Verified by Project Engineering Team</Text></>; }
function SplitMedia({ onPreview, count, more }: { onPreview: (x: string) => void; count: number; more: string }) { return <><View style={s.splitGallery}>{Array.from({ length: count }, (_, i) => <Thumb key={i} index={i + 1} more={i === count - 1 ? more : undefined} onPreview={onPreview} />)}</View><View style={s.actions}><Action label="View 5 Photos" text="View 5 photos" icon="photo" onPress={() => onPreview("Project photo gallery")} /><Action label="Preview Foundation QA Report" text="Foundation QA Report.pdf" icon="file" onPress={() => onPreview("Foundation QA Report")}/></View></>; }
function SingleMedia({ onPreview }: { onPreview: (x: string) => void }) { return <View style={s.singleWrap}><Thumb index={2} more="+4" onPreview={onPreview} /><Action label="View 4 Photos" text="View 4 photos" icon="photo" onPress={() => onPreview("Project photo gallery")} /></View>; }
function Action({ label, text, icon, onPress }: { label: string; text: string; icon: "photo" | "file"; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={s.action}><Icon name={icon} gold /><Text numberOfLines={1} style={s.actionText}>{text}</Text></Pressable>; }
function Fact({ label, value }: { label: string; value: string }) { return <View style={s.fact}><Text style={s.nextLabel}>{label}</Text><Text style={s.factValue}>{value}</Text></View>; }
function PreviewModal({ preview, photo, close }: { preview: string | null; photo: ImageSourcePropType; close: () => void }) { return <Modal transparent visible={!!preview} animationType="fade" onRequestClose={close}><View style={s.modalShade}><View style={s.modal}><Text style={s.heading}>{preview}</Text><Text style={s.modalText}>This is an honest local demo preview for the Karaa prototype. It is not a live project document or delivery record.</Text>{preview?.toLowerCase().includes("photo") ? <Image accessibilityLabel={`${preview} preview`} resizeMode="cover" source={photo} style={s.previewImage} /> : <View style={s.paper}><Text style={s.paperTitle}>DEMO PROJECT RECORD</Text><Text style={s.intro}>Preview-only sample attachment. No external file has been fetched.</Text></View>}<Pressable accessibilityRole="button" accessibilityLabel="Close preview" onPress={close} style={s.close}><Text style={s.closeText}>Close</Text></Pressable></View></View></Modal>; }
const cap = (x: string) => x[0].toUpperCase() + x.slice(1);
const GOLD = "#C98A18", INK = "#28251F", LINE = "#E6E0D5";
export const projectDetailResponsiveMetrics = { pageGutter: 16, filterGap: 4, filterMinFont: 10, touchTarget: 44, supportedWidths: [360, 390, 430] } as const;
export const s = StyleSheet.create({
  page: { backgroundColor: "#FBFAF7", marginHorizontal: -16, paddingBottom: 14 },
  summary: { backgroundColor: "#FFF", paddingHorizontal: 16, paddingTop: 8, paddingBottom: 7 },
  eyebrow: { color: "#8A7D68", fontSize: 10, fontWeight: "700", letterSpacing: .35, marginBottom: 6 },
  summaryTop: { flexDirection: "row", gap: 10 }, hero: { width: 126, height: 105, borderRadius: 2 }, summaryCopy: { flex: 1, paddingTop: 2 },
  name: { fontFamily: "serif", fontSize: 20, color: INK, lineHeight: 23 }, location: { fontSize: 11, color: "#746E64", marginTop: 4 }, status: { color: "#4D8756", fontSize: 10, fontWeight: "800", marginTop: 5 },
  metrics: { flexDirection: "row", marginTop: 7 }, metric: { width: "33.333%" }, metricBig: { fontFamily: "serif", fontSize: 20, color: GOLD, lineHeight: 21 }, metricDate: { fontFamily: undefined, fontSize: 11, color: INK, fontWeight: "700", paddingTop: 5 }, metricLabel: { fontSize: 10, color: "#777168", marginTop: 1 },
  progressRow: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 5 }, rail: { flex: 1, height: 2, backgroundColor: "#EBE5DC" }, fill: { height: 2, backgroundColor: GOLD }, progressLabel: { fontSize: 10, color: "#777168" },
  tabs: { height: 48, flexDirection: "row", backgroundColor: "#FFF", borderTopWidth: 1, borderBottomWidth: 1, borderColor: LINE }, tab: { flex: 1, minHeight: 44, flexDirection: "row", gap: 5, alignItems: "center", justifyContent: "center", borderBottomWidth: 2, borderBottomColor: "transparent" }, tabOn: { borderBottomColor: GOLD }, tabText: { fontSize: 10, color: "#504B44", fontWeight: "700" }, icon: { fontSize: 12, color: "#5F5A52" }, gold: { color: GOLD },
  body: { paddingHorizontal: 16, paddingTop: 9 }, filters: { flexDirection: "row", gap: 4, marginBottom: 8 }, chip: { flex: 1, height: 32, minWidth: 0, paddingHorizontal: 2, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: LINE, borderRadius: 3, backgroundColor: "#FFF" }, chipOn: { backgroundColor: "#FFF7E7", borderColor: GOLD }, chipText: { fontSize: 10, color: "#615C54", fontWeight: "700" },
  heading: { fontFamily: "serif", fontSize: 23, lineHeight: 27, color: INK }, intro: { fontSize: 12, color: "#777168", lineHeight: 17, marginTop: 1 }, muted: { fontSize: 11, color: "#777168", marginTop: 1 }, timeline: { marginTop: 7 },
  timelineRow: { paddingLeft: 30, position: "relative", paddingBottom: 8 }, line: { position: "absolute", left: 8, top: 0, bottom: -1, width: 1, backgroundColor: GOLD }, lineLast: { bottom: 16 }, lineFuture: { backgroundColor: "#CFC9BE" }, node: { position: "absolute", left: 1, top: 8, width: 15, height: 15, borderRadius: 8, alignItems: "center", justifyContent: "center", backgroundColor: "#FFF", borderWidth: 1.5, borderColor: GOLD }, nodeDone: { backgroundColor: GOLD }, nodeCurrent: { width: 17, height: 17, left: 0, top: 7, shadowColor: GOLD, shadowOpacity: .28, shadowRadius: 5 }, nodeCore: { width: 5, height: 5, borderRadius: 3, backgroundColor: GOLD }, nodeUpcoming: { borderColor: "#BEB8AE", backgroundColor: "#FFF" }, tick: { color: "#FFF", fontSize: 10, lineHeight: 11, fontWeight: "900" },
  event: { minHeight: 64, backgroundColor: "#FFF", borderColor: LINE, borderWidth: 1, borderRadius: 5, padding: 9, position: "relative" }, featured: { backgroundColor: "#FFFCF4", borderColor: "#E7C577" }, meta: { flexDirection: "row", alignItems: "center", gap: 7 }, date: { fontSize: 10, color: GOLD, fontWeight: "900" }, badge: { fontSize: 10, color: "#4B8051", fontWeight: "900", backgroundColor: "#EEF6ED", paddingHorizontal: 5, paddingVertical: 2, borderRadius: 2 }, badgeUpcoming: { color: "#777168", backgroundColor: "#F1F0ED" }, eventTitle: { fontFamily: "serif", fontSize: 17, lineHeight: 20, color: INK, marginTop: 4 }, detail: { fontSize: 12, color: "#625D55", lineHeight: 16, marginTop: 2 },
  gallery: { flexDirection: "row", gap: 5, marginTop: 7 }, thumbTarget: { flex: 1, minWidth: 0, height: 58, position: "relative" }, photo: { width: "100%", height: "100%", borderRadius: 2 }, moreShade: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0, backgroundColor: "rgba(22,20,17,.42)", alignItems: "center", justifyContent: "center", borderRadius: 2 }, more: { color: "#FFF", fontSize: 13, fontWeight: "800" },
  actions: { flexDirection: "row", gap: 5, marginTop: 5 }, action: { flex: 1, minWidth: 0, minHeight: 44, borderColor: LINE, borderWidth: 1, borderRadius: 3, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 4, paddingHorizontal: 4, backgroundColor: "#FFF" }, actionText: { fontSize: 10, color: "#6A5940", fontWeight: "700", flexShrink: 1 }, verified: { fontSize: 10, color: "#777168", marginTop: 4 },
  splitGallery: { position: "absolute", right: 8, top: 8, width: 128, height: 58, flexDirection: "row", gap: 4 }, singleWrap: { position: "absolute", right: 8, top: 8, width: 112, gap: 3 }, sideMediaCopy: { paddingRight: 136, minHeight: 64 }, approvalCopy: { paddingRight: 112 }, statusPanel: { position: "absolute", right: 8, top: 9, width: 103, padding: 7, borderWidth: 1, borderColor: LINE, borderRadius: 3, backgroundColor: "#FAFBF8" }, approved: { fontSize: 10, color: "#4B8051", fontWeight: "800" }, onSchedule: { fontSize: 10, color: "#777168", marginTop: 5 }, planned: { fontSize: 10, color: GOLD, fontWeight: "700", marginTop: 5 },
  next: { minHeight: 70, borderColor: "#E7C577", borderWidth: 1, borderRadius: 5, marginTop: 3, padding: 8, flexDirection: "row", alignItems: "center", backgroundColor: "#FFFCF4" }, nextBell: { width: 28, height: 28, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#F9EDD2" }, nextCopy: { flex: 1, marginLeft: 7 }, nextLabel: { fontSize: 10, color: GOLD, fontWeight: "900", textTransform: "uppercase" }, nextTitle: { fontFamily: "serif", fontSize: 16, color: INK }, notify: { alignItems: "center", flexDirection: "row", gap: 3 }, notifyText: { fontSize: 10, fontWeight: "700", color: "#504B44" }, notifySwitch: { width: 44, height: 44 },
  fact: { borderBottomWidth: 1, borderColor: LINE, paddingVertical: 14 }, factValue: { fontSize: 13, color: INK, marginTop: 5 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 5, marginTop: 9 }, gridItem: { width: "32%", minHeight: 90 }, gridPhoto: { width: "100%", height: 90, borderRadius: 3 },
  modalShade: { flex: 1, backgroundColor: "rgba(0,0,0,.68)", justifyContent: "center", padding: 24 }, modal: { backgroundColor: "#FFF", borderRadius: 8, padding: 18 }, modalText: { fontSize: 12, color: "#625D55", lineHeight: 17, marginTop: 8 }, previewImage: { width: "100%", height: 190, marginTop: 12 }, paper: { height: 150, backgroundColor: "#F6F3EA", marginTop: 12, padding: 18, borderWidth: 1, borderColor: LINE }, paperTitle: { fontSize: 11, color: GOLD, fontWeight: "900" }, close: { height: 44, backgroundColor: INK, alignItems: "center", justifyContent: "center", marginTop: 14, borderRadius: 4 }, closeText: { color: "#FFF", fontWeight: "800" },
});
