import type { ImageSourcePropType } from 'react-native';

export type MatterIcon = 'continuity' | 'connection' | 'resilience' | 'learning' | 'place' | 'energy' | 'care' | 'flow' | 'stewardship';
export type VerticalDetail = {
  id: string; number: string; title: string; intro: string; hero: ImageSourcePropType;
  pathways: { title: string; description: string; image: ImageSourcePropType; routeId?: string }[];
  mattersTitle: string;
  matters: { title: string; copy: string; icon: MatterIcon; iconLabel?: string }[];
};

const generated = {
  '01': [require('../../assets/verticals/generated/01-infrastructure-urban-development/hero.webp'), require('../../assets/verticals/generated/01-infrastructure-urban-development/01.webp'), require('../../assets/verticals/generated/01-infrastructure-urban-development/02.webp'), require('../../assets/verticals/generated/01-infrastructure-urban-development/03.webp'), require('../../assets/verticals/generated/01-infrastructure-urban-development/04.webp')],
  '02': [require('../../assets/verticals/generated/02-ports-airports-logistics/hero.webp'), require('../../assets/verticals/generated/02-ports-airports-logistics/01.webp'), require('../../assets/verticals/generated/02-ports-airports-logistics/02.webp'), require('../../assets/verticals/generated/02-ports-airports-logistics/03.webp'), require('../../assets/verticals/generated/02-ports-airports-logistics/04.webp')],
  '03': [require('../../assets/verticals/generated/03-energy-utilities/hero.webp'), require('../../assets/verticals/generated/03-energy-utilities/01.webp'), require('../../assets/verticals/generated/03-energy-utilities/02.webp'), require('../../assets/verticals/generated/03-energy-utilities/03.webp'), require('../../assets/verticals/generated/03-energy-utilities/04.webp')],
  '05': [require('../../assets/verticals/generated/05-hospitality-tourism-leisure/hero.webp'), require('../../assets/verticals/generated/05-hospitality-tourism-leisure/01.webp'), require('../../assets/verticals/generated/05-hospitality-tourism-leisure/02.webp'), require('../../assets/verticals/generated/05-hospitality-tourism-leisure/03.webp'), require('../../assets/verticals/generated/05-hospitality-tourism-leisure/04.webp')],
  '06': [require('../../assets/verticals/generated/06-real-estate-asset-development/hero.webp'), require('../../assets/verticals/generated/06-real-estate-asset-development/01.webp'), require('../../assets/verticals/generated/06-real-estate-asset-development/02.webp'), require('../../assets/verticals/generated/06-real-estate-asset-development/03.webp'), require('../../assets/verticals/generated/06-real-estate-asset-development/04.webp')],
  '07': [require('../../assets/verticals/generated/07-manufacturing-industrial-solutions/hero.webp'), require('../../assets/verticals/generated/07-manufacturing-industrial-solutions/01.webp'), require('../../assets/verticals/generated/07-manufacturing-industrial-solutions/02.webp'), require('../../assets/verticals/generated/07-manufacturing-industrial-solutions/03.webp'), require('../../assets/verticals/generated/07-manufacturing-industrial-solutions/04.webp')],
  '08': [require('../../assets/verticals/generated/08-spiritual-renaissance-for-bharat/hero.webp'), require('../../assets/verticals/generated/08-spiritual-renaissance-for-bharat/01.webp'), require('../../assets/verticals/generated/08-spiritual-renaissance-for-bharat/02.webp'), require('../../assets/verticals/generated/08-spiritual-renaissance-for-bharat/03.webp'), require('../../assets/verticals/generated/08-spiritual-renaissance-for-bharat/04.webp')],
  '09': [require('../../assets/verticals/generated/09-education-technology-innovation/hero.webp'), require('../../assets/verticals/generated/09-education-technology-innovation/01.webp'), require('../../assets/verticals/generated/09-education-technology-innovation/02.webp'), require('../../assets/verticals/generated/09-education-technology-innovation/03.webp'), require('../../assets/verticals/generated/09-education-technology-innovation/04.webp')],
} as const;
const pathwayCopy: Record<string,string> = {
  'Transport Infrastructure: Roads, Highways, Metro & Rail':'Connected mobility built for everyday life.','Smart Cities & Complete Human Ecosystems':'Human-centred districts where systems work together.','Industrial Parks & Economic Districts':'Productive districts designed for lasting growth.','EPC & Turnkey Development':'Clear delivery from concept through completion.',
  'Seaports & Airports':'Dependable gateways connecting people and trade.','Cargo Terminals & Warehousing':'Efficient storage and cargo movement at scale.','Multimodal Logistics Corridors':'Seamless links across road, rail, sea and air.','Supply Chain & Market Connectivity':'Stronger routes from producers to markets.',
  'Renewable Energy & Green Hydrogen':'Clean power for a lower-carbon future.','Power Generation':'Reliable generation for growing communities.','Transmission, Distribution & Smart Utilities':'Smarter networks delivering power dependably.','EV, Clean Energy & Resource Efficiency':'Cleaner mobility with more efficient resources.',
  'Hotels & Resorts':'Welcoming stays grounded in local character.','Convention Centres & Business Tourism':'Purposeful venues for ideas and enterprise.','Wellness & Retreats':'Restorative places for body and mind.','Cruises, Destinations & Leisure Experiences':'Memorable journeys shaped around discovery.',
  'Residential Communities':'Thoughtful homes connected to daily life.','Commercial Developments':'Adaptable workplaces built for enterprise.','Industrial & Mixed-Use Assets':'Flexible assets combining work, life and industry.','Asset Management & Lifecycle Value':'Stewardship that protects value over time.',
  'Advanced Manufacturing':'Precise, scalable production for modern industry.','Engineering & Heavy Systems':'Robust engineering for demanding operations.','Industrial & Renewable-Energy Equipment':'Equipment enabling productive, cleaner systems.','Quality, Innovation & Scale':'Better processes that grow without compromise.',
  'Spiritual Knowledge & Education':'Living wisdom shared across generations.','Heritage & Culture Revival':'Culture and heritage renewed with care.','Temples, Ashrams & Pilgrimage Facilities':'Dignified places for devotion and gathering.','Yoga, Ayurveda, Wellness & Values-Led Nation Building':'Timeless wellbeing guiding collective progress.',
  'Universities & Institutes':'Learning environments that expand possibility.','Skill Development & Industry Alignment':'Practical skills connected to real opportunity.','AI & Emerging Technology':'Responsible technology for tomorrow’s challenges.','Research, Innovation, Incubation & Startups':'Ideas supported from discovery to enterprise.',
};
const pathway = (titles: string[], images: readonly ImageSourcePropType[]) => titles.map((title, index) => ({ title, description: pathwayCopy[title], image: images[index] }));
const matters = (rows: [string, string][], icons: MatterIcon[] = ['continuity','connection','resilience']) => rows.map(([title, copy], index) => ({ title, copy, icon: icons[index] }));

export const verticalDetails: VerticalDetail[] = [
  { id:'infrastructure-urban-development', number:'01', title:'Infrastructure & Urban Development', intro:'Places, systems and city-scale frameworks conceived for long-term public value.', hero:generated['01'][0], pathways:pathway(['Transport Infrastructure: Roads, Highways, Metro & Rail','Smart Cities & Complete Human Ecosystems','Industrial Parks & Economic Districts','EPC & Turnkey Development'],generated['01'].slice(1)), mattersTitle:'Places built around people', matters:matters([['Plan at human scale','Plan connected districts around everyday movement, civic access and long-term public value.'],['Connect growth with continuity','Bring transport, utilities and human ecosystems together with disciplined execution.'],['Build for resilient use','Create resilient urban capacity that can serve communities across generations.']]) },
  { id:'ports-airports-logistics', number:'02', title:'Ports, Airports & Integrated Logistics', intro:'Connected infrastructure that helps movement, trade and access work together.', hero:generated['02'][0], pathways:pathway(['Seaports & Airports','Cargo Terminals & Warehousing','Multimodal Logistics Corridors','Supply Chain & Market Connectivity'],generated['02'].slice(1)), mattersTitle:'Movement without friction', matters:matters([['Connect key gateways','Strengthen gateway infrastructure that improves movement, trade and dependable access.'],['Design for dependable flow','Connect cargo, warehousing and multimodal corridors into clear operating systems.'],['Strengthen market access','Improve flow, market reach and national-scale logistics continuity.']]) },
  { id:'energy-utilities', number:'03', title:'Energy & Utilities', intro:'Energy and utility systems considered through reliability, efficiency and stewardship.', hero:generated['03'][0], pathways:pathway(['Renewable Energy & Green Hydrogen','Power Generation','Transmission, Distribution & Smart Utilities','EV, Clean Energy & Resource Efficiency'],generated['03'].slice(1)), mattersTitle:'Powering responsible progress', matters:matters([['Advance resilient systems','Design reliable energy systems that support growth without losing sight of stewardship.'],['Use resources responsibly','Bring generation, distribution and smart utility thinking into one connected view.'],['Support clean transition','Support cleaner transition, resource efficiency and dependable service continuity.']]) },
  { id:'healthcare-life-sciences', number:'04', title:'Healthcare & Life Sciences', intro:'Building integrated healthcare systems that improve access, quality and outcomes across care delivery, diagnostics, digital health and life sciences.', hero:require('../../assets/verticals/healthcare-hero-user-supplied.webp'), pathways:[
    { title:'Multi-Specialty Hospitals', description:'Connected, people-first care.', image:require('../../assets/verticals/multi-specialty-hospitals-user-supplied.webp') },
    { title:'Diagnostics, Clinics & Preventive Health', description:'Earlier insight, healthier lives.', image:require('../../assets/verticals/diagnostics-clinics-preventive-health-user-supplied.webp') },
    { title:'Digital Health & Telemedicine', description:'Care that reaches every need.', routeId:'digital-health-telemedicine-emergency-response', image:require('../../assets/verticals/digital-health-telemedicine-user-supplied.webp') },
    { title:'Medical Education, Life Sciences & Research', description:'Learning and research for health.', image:require('../../assets/verticals/medical-education-life-sciences-research-user-supplied.webp') },
  ], mattersTitle:'Care designed as a continuum', matters:matters([['Care beyond the point of need','True healthcare transcends illness, from primary care to specialty services, response and follow-through.'],['What it brings together','Hospitals, labs, preventive platforms and digital innovation can strengthen outcomes together.'],['Why continuity matters','Every stakeholder aligned and every outcome enduring across the care continuum.']],['care','connection','continuity']) },
  { id:'hospitality-tourism-leisure', number:'05', title:'Hospitality, Tourism & Leisure', intro:'Destination and hospitality environments considered around memorable human experience.', hero:generated['05'][0], pathways:pathway(['Hotels & Resorts','Convention Centres & Business Tourism','Wellness & Retreats','Cruises, Destinations & Leisure Experiences'],generated['05'].slice(1)), mattersTitle:'Experience rooted in place', matters:matters([['Create a sense of place','Create memorable destinations grounded in service, comfort and a strong sense of place.'],['Serve people well','Connect hospitality, wellness, business tourism and leisure into elevated guest experiences.'],['Build enduring destinations','Build destinations that remain attractive, useful and enduring over time.']]) },
  { id:'real-estate-asset-development', number:'06', title:'Real Estate & Asset Development', intro:'Built environments approached as long-life assets for communities and organisations.', hero:generated['06'][0], pathways:pathway(['Residential Communities','Commercial Developments','Industrial & Mixed-Use Assets','Asset Management & Lifecycle Value'],generated['06'].slice(1)), mattersTitle:'Value beyond handover', matters:matters([['Think beyond handover','Shape communities and commercial assets around daily life, access and durability.'],['Design for daily life','Bring design, development, operations and lifecycle value into one disciplined asset view.'],['Protect long-term value','Protect long-term value through usefulness, adaptability and careful stewardship.']]) },
  { id:'manufacturing-industrial-solutions', number:'07', title:'Manufacturing & Industrial Solutions', intro:'Industrial capacity shaped by operating discipline, quality and responsible scale.', hero:generated['07'][0], pathways:pathway(['Advanced Manufacturing','Engineering & Heavy Systems','Industrial & Renewable-Energy Equipment','Quality, Innovation & Scale'],generated['07'].slice(1)), mattersTitle:'Capability built to last', matters:matters([['Engineer with clarity','Build industrial capability with clarity, quality and responsible scale.'],['Maintain quality at scale','Connect engineering, equipment, process discipline and innovation into practical capacity.'],['Build useful capability','Strengthen productive systems that can serve markets reliably over time.']]) },
  { id:'spiritual-renaissance-for-bharat', number:'08', title:'Spiritual Renaissance for Bharat', intro:'Cultural and values-led spaces considered with care for learning, heritage and collective life.', hero:generated['08'][0], pathways:pathway(['Spiritual Knowledge & Education','Heritage & Culture Revival','Temples, Ashrams & Pilgrimage Facilities','Yoga, Ayurveda, Wellness & Values-Led Nation Building'],generated['08'].slice(1)), mattersTitle:'Heritage carried forward', matters:matters([['Respect living heritage','Respect living heritage while creating spaces for learning, pilgrimage and shared values.'],['Create places for learning','Bring culture, wellness, education and place-making into thoughtful spiritual ecosystems.'],['Build with cultural care','Support continuity of tradition through dignified, useful and enduring environments.']]) },
  { id:'education-technology-innovation', number:'09', title:'Education, Technology & Innovation', intro:'Learning and innovation ecosystems built for people, capability and the future of work.', hero:generated['09'][0], pathways:pathway(['Universities & Institutes','Skill Development & Industry Alignment','AI & Emerging Technology','Research, Innovation, Incubation & Startups'],generated['09'].slice(1)), mattersTitle:'Learning connected to opportunity', matters:matters([['Make learning useful','Make learning practical, future-facing and connected to real opportunity.'],['Support practical discovery','Bring institutions, skills, emerging technology and incubation into capability ecosystems.'],['Connect ideas to opportunity','Turn ideas into durable progress through research, innovation and applied discovery.']]) },
];

export const verticalDetailForId = (id: string) => verticalDetails.find((item) => item.id === id) ?? verticalDetails[0];
