import type { ImageSourcePropType } from 'react-native';

export type VerticalDetail = {
  id: string; number: string; title: string; intro: string; hero: ImageSourcePropType;
  pathways: { title: string; description: string; image: ImageSourcePropType }[];
  mattersTitle: string;
  matters: { title: string; copy: string; icon: string }[];
};

const urban = require('../../assets/verticals/conceptual-urban-district.png');
const logistics = require('../../assets/verticals/conceptual-logistics-port.png');
const energy = require('../../assets/verticals/conceptual-clean-energy.png');
const healthcareCampus = require('../../assets/verticals/conceptual-healthcare-campus.png');
const cardImages = [urban, logistics, energy, healthcareCampus];
const pathway = (titles: string[], offset: number) => titles.map((title, index) => ({ title, description: 'Integrated capability, disciplined delivery and long-term value across the complete ecosystem.', image: cardImages[(offset + index) % cardImages.length] }));
const matters = (rows: [string, string][]) => rows.map(([title, copy], index) => ({ title, copy, icon: ['◎', '⌁', '◇'][index] }));

export const verticalDetails: VerticalDetail[] = [
  { id:'infrastructure-urban-development', number:'01', title:'Infrastructure & Urban Development', intro:'Places, systems and city-scale frameworks conceived for long-term public value.', hero:urban, pathways:pathway(['Transport Infrastructure: Roads, Highways, Metro & Rail','Smart Cities & Complete Human Ecosystems','Industrial Parks & Economic Districts','EPC & Turnkey Development'],0), mattersTitle:'Places built around people', matters:matters([['Plan at human scale','Plan connected districts around everyday movement, civic access and long-term public value.'],['Connect growth with continuity','Bring transport, utilities and human ecosystems together with disciplined execution.'],['Build for resilient use','Create resilient urban capacity that can serve communities across generations.']]) },
  { id:'ports-airports-logistics', number:'02', title:'Ports, Airports & Integrated Logistics', intro:'Connected infrastructure that helps movement, trade and access work together.', hero:logistics, pathways:pathway(['Seaports & Airports','Cargo Terminals & Warehousing','Multimodal Logistics Corridors','Supply Chain & Market Connectivity'],1), mattersTitle:'Movement without friction', matters:matters([['Connect key gateways','Strengthen gateway infrastructure that improves movement, trade and dependable access.'],['Design for dependable flow','Connect cargo, warehousing and multimodal corridors into clear operating systems.'],['Strengthen market access','Improve flow, market reach and national-scale logistics continuity.']]) },
  { id:'energy-utilities', number:'03', title:'Energy & Utilities', intro:'Energy and utility systems considered through reliability, efficiency and stewardship.', hero:energy, pathways:pathway(['Renewable Energy & Green Hydrogen','Power Generation','Transmission, Distribution & Smart Utilities','EV, Clean Energy & Resource Efficiency'],2), mattersTitle:'Powering responsible progress', matters:matters([['Advance resilient systems','Design reliable energy systems that support growth without losing sight of stewardship.'],['Use resources responsibly','Bring generation, distribution and smart utility thinking into one connected view.'],['Support clean transition','Support cleaner transition, resource efficiency and dependable service continuity.']]) },
  { id:'healthcare-life-sciences', number:'04', title:'Healthcare & Life Sciences', intro:'Building integrated healthcare systems that improve access, quality and outcomes across care delivery, diagnostics, digital health and life sciences.', hero:require('../../assets/verticals/healthcare-hero-user-supplied.png'), pathways:[
    { title:'Multi-Specialty Hospitals', description:'Integrated care environments designed around people, clinical excellence and continuity.', image:require('../../assets/verticals/multi-specialty-hospitals-user-supplied.png') },
    { title:'Diagnostics, Clinics & Preventive Health', description:'Early detection, connected diagnostics and proactive care for healthier communities.', image:require('../../assets/verticals/diagnostics-clinics-preventive-health-user-supplied.png') },
    { title:'Digital Health, Telemedicine & Emergency Response', description:'Technology-enabled care that extends access, responsiveness and reach.', image:require('../../assets/verticals/digital-health-telemedicine-user-supplied.png') },
    { title:'Medical Education, Life Sciences & Research', description:'Knowledge, talent and research working together to strengthen the future of health.', image:require('../../assets/verticals/medical-education-life-sciences-research-user-supplied.png') },
  ], mattersTitle:'Care designed as a continuum', matters:matters([['Care beyond the point of need','True healthcare transcends illness, from primary care to specialty services, response and follow-through.'],['What it brings together','Hospitals, labs, preventive platforms and digital innovation can strengthen outcomes together.'],['Why continuity matters','Every stakeholder aligned and every outcome enduring across the care continuum.']]) },
  { id:'hospitality-tourism-leisure', number:'05', title:'Hospitality, Tourism & Leisure', intro:'Destination and hospitality environments considered around memorable human experience.', hero:require('../../assets/verticals/conceptual-hospitality-resort.png'), pathways:pathway(['Hotels & Resorts','Convention Centres & Business Tourism','Wellness & Retreats','Cruises, Destinations & Leisure Experiences'],0), mattersTitle:'Experience rooted in place', matters:matters([['Create a sense of place','Create memorable destinations grounded in service, comfort and a strong sense of place.'],['Serve people well','Connect hospitality, wellness, business tourism and leisure into elevated guest experiences.'],['Build enduring destinations','Build destinations that remain attractive, useful and enduring over time.']]) },
  { id:'real-estate-asset-development', number:'06', title:'Real Estate & Asset Development', intro:'Built environments approached as long-life assets for communities and organisations.', hero:require('../../assets/verticals/conceptual-real-estate-district.png'), pathways:pathway(['Residential Communities','Commercial Developments','Industrial & Mixed-Use Assets','Asset Management & Lifecycle Value'],1), mattersTitle:'Value beyond handover', matters:matters([['Think beyond handover','Shape communities and commercial assets around daily life, access and durability.'],['Design for daily life','Bring design, development, operations and lifecycle value into one disciplined asset view.'],['Protect long-term value','Protect long-term value through usefulness, adaptability and careful stewardship.']]) },
  { id:'manufacturing-industrial-solutions', number:'07', title:'Manufacturing & Industrial Solutions', intro:'Industrial capacity shaped by operating discipline, quality and responsible scale.', hero:require('../../assets/verticals/conceptual-advanced-manufacturing.png'), pathways:pathway(['Advanced Manufacturing','Engineering & Heavy Systems','Industrial & Renewable-Energy Equipment','Quality, Innovation & Scale'],2), mattersTitle:'Capability built to last', matters:matters([['Engineer with clarity','Build industrial capability with clarity, quality and responsible scale.'],['Maintain quality at scale','Connect engineering, equipment, process discipline and innovation into practical capacity.'],['Build useful capability','Strengthen productive systems that can serve markets reliably over time.']]) },
  { id:'spiritual-renaissance-for-bharat', number:'08', title:'Spiritual Renaissance for Bharat', intro:'Cultural and values-led spaces considered with care for learning, heritage and collective life.', hero:require('../../assets/verticals/conceptual-spiritual-heritage.png'), pathways:pathway(['Spiritual Knowledge & Education','Heritage & Culture Revival','Temples, Ashrams & Pilgrimage Facilities','Yoga, Ayurveda, Wellness & Values-Led Nation Building'],3), mattersTitle:'Heritage carried forward', matters:matters([['Respect living heritage','Respect living heritage while creating spaces for learning, pilgrimage and shared values.'],['Create places for learning','Bring culture, wellness, education and place-making into thoughtful spiritual ecosystems.'],['Build with cultural care','Support continuity of tradition through dignified, useful and enduring environments.']]) },
  { id:'education-technology-innovation', number:'09', title:'Education, Technology & Innovation', intro:'Learning and innovation ecosystems built for people, capability and the future of work.', hero:require('../../assets/verticals/conceptual-education-innovation.png'), pathways:pathway(['Universities & Institutes','Skill Development & Industry Alignment','AI & Emerging Technology','Research, Innovation, Incubation & Startups'],0), mattersTitle:'Learning connected to opportunity', matters:matters([['Make learning useful','Make learning practical, future-facing and connected to real opportunity.'],['Support practical discovery','Bring institutions, skills, emerging technology and incubation into capability ecosystems.'],['Connect ideas to opportunity','Turn ideas into durable progress through research, innovation and applied discovery.']]) },
];

export const verticalDetailForId = (id: string) => verticalDetails.find((item) => item.id === id) ?? verticalDetails[0];
